---
- hosts: managers
  become: true
  roles:
  - docker
  - manager

- hosts: worker
  become: true
  roles:
  - docker
  - worker
  
- hosts: managers
  become: true
  roles:
  - managerclonerepo
  - stackdeploy